"""Drafts — Draft dataclass + persist helpers + lookups."""

import json
from dataclasses import dataclass, field
from typing import Literal

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

Language = Literal["NL", "FR", "EN"]


@dataclass(frozen=True)
class Draft:
    """A single piece of marketing content generated by the agent."""

    action_type_name: str  # must match a seeded action_types.name
    channel: str  # e.g., "tiktok", "instagram", "email", "seo"
    language: Language
    copy: str
    asset_path: str | None  # filesystem path or None for text-only
    generation_cost_cents: int  # rounded; Claude tokens cost converted
    brand_score: int  # 0-100, set by brand-quality gate
    visual_truthfulness_pass: bool  # True for text-only drafts
    metadata: dict = field(default_factory=dict)


@dataclass(frozen=True)
class VideoAsset:
    """A Slack video file attached to a draft's review thread."""

    draft_id: int
    slack_file_id: str
    thread_ts: str
    path: str
    role: Literal["source", "combined"]
    mime_type: str
    size_bytes: int
    duration_seconds: float | None
    width: int | None
    height: int | None
    status: str
    review: dict
    message_ts: str = ""


async def persist_draft(engine: AsyncEngine, draft: Draft) -> int:
    """Insert a draft row, return its id. Raises ValueError if action_type unknown."""
    async with engine.begin() as conn:
        action_id_row = (
            await conn.execute(
                text("SELECT id FROM action_types WHERE name = :n"),
                {"n": draft.action_type_name},
            )
        ).fetchone()
        if action_id_row is None:
            raise ValueError(f"unknown action_type: {draft.action_type_name!r}")
        action_type_id = action_id_row[0]

        new_id_row = (
            await conn.execute(
                text(
                    "INSERT INTO drafts "
                    "(action_type_id, channel, language, copy, asset_path, "
                    " generation_cost_cents, brand_score, visual_truthfulness_pass, metadata) "
                    "VALUES (:atid, :ch, :lang, :copy, :ap, :cost, :bs, :vtp, CAST(:meta AS JSONB)) "
                    "RETURNING id"
                ),
                {
                    "atid": action_type_id,
                    "ch": draft.channel,
                    "lang": draft.language,
                    "copy": draft.copy,
                    "ap": draft.asset_path,
                    "cost": draft.generation_cost_cents,
                    "bs": draft.brand_score,
                    "vtp": draft.visual_truthfulness_pass,
                    "meta": json.dumps(draft.metadata or {}),
                },
            )
        ).fetchone()
    return int(new_id_row[0])


async def persist_video_asset(engine: AsyncEngine, asset: VideoAsset) -> int:
    """Persist a Slack video asset, returning its existing ID on duplicate upload."""
    async with engine.begin() as conn:
        inserted_row = (
            await conn.execute(
                text(
                    "INSERT INTO video_assets "
                    "(draft_id, slack_file_id, thread_ts, message_ts, path, role, mime_type, size_bytes, "
                    " duration_seconds, width, height, status, review) "
                    "VALUES (:draft_id, :slack_file_id, :thread_ts, :message_ts, :path, :role, :mime_type, "
                    " :size_bytes, :duration_seconds, :width, :height, :status, CAST(:review AS JSONB)) "
                    "ON CONFLICT (draft_id, slack_file_id) DO NOTHING "
                    "RETURNING id"
                ),
                {
                    "draft_id": asset.draft_id,
                    "slack_file_id": asset.slack_file_id,
                    "thread_ts": asset.thread_ts,
                    "message_ts": asset.message_ts,
                    "path": asset.path,
                    "role": asset.role,
                    "mime_type": asset.mime_type,
                    "size_bytes": asset.size_bytes,
                    "duration_seconds": asset.duration_seconds,
                    "width": asset.width,
                    "height": asset.height,
                    "status": asset.status,
                    "review": json.dumps(asset.review or {}),
                },
            )
        ).fetchone()
        if inserted_row is not None:
            return int(inserted_row[0])

        existing_row = (
            await conn.execute(
                text(
                    "SELECT id FROM video_assets "
                    "WHERE draft_id = :draft_id AND slack_file_id = :slack_file_id"
                ),
                {"draft_id": asset.draft_id, "slack_file_id": asset.slack_file_id},
            )
        ).fetchone()
    return int(existing_row[0])


def _video_asset_from_row(row) -> VideoAsset:
    return VideoAsset(
        draft_id=row[0],
        slack_file_id=row[1],
        thread_ts=row[2],
        path=row[3],
        role=row[4],
        mime_type=row[5],
        size_bytes=row[6],
        duration_seconds=row[7],
        width=row[8],
        height=row[9],
        status=row[10],
        review=row[11],
        message_ts=row[12],
    )


async def claim_video_asset(engine: AsyncEngine, asset: VideoAsset) -> tuple[VideoAsset, bool]:
    """Atomically claim a Slack upload, returning an existing claim to duplicate workers."""
    lock_key = f"video-asset:{asset.draft_id}:{asset.slack_file_id}"
    async with engine.begin() as conn:
        await conn.execute(
            text("SELECT pg_advisory_xact_lock(hashtextextended(:lock_key, 0))"),
            {"lock_key": lock_key},
        )
        existing = (
            await conn.execute(
                text(
                    "SELECT draft_id, slack_file_id, thread_ts, path, role, mime_type, size_bytes, "
                    "duration_seconds, width, height, status, review, message_ts "
                    "FROM video_assets WHERE draft_id = :draft_id AND slack_file_id = :slack_file_id"
                ),
                {"draft_id": asset.draft_id, "slack_file_id": asset.slack_file_id},
            )
        ).fetchone()
        if existing is not None:
            return _video_asset_from_row(existing), False
        await conn.execute(
            text(
                "INSERT INTO video_assets "
                "(draft_id, slack_file_id, thread_ts, message_ts, path, role, mime_type, size_bytes, "
                " duration_seconds, width, height, status, review) "
                "VALUES (:draft_id, :slack_file_id, :thread_ts, :message_ts, :path, :role, :mime_type, "
                " :size_bytes, :duration_seconds, :width, :height, :status, CAST(:review AS JSONB))"
            ),
            {
                "draft_id": asset.draft_id,
                "slack_file_id": asset.slack_file_id,
                "thread_ts": asset.thread_ts,
                "message_ts": asset.message_ts,
                "path": asset.path,
                "role": asset.role,
                "mime_type": asset.mime_type,
                "size_bytes": asset.size_bytes,
                "duration_seconds": asset.duration_seconds,
                "width": asset.width,
                "height": asset.height,
                "status": asset.status,
                "review": json.dumps(asset.review or {}),
            },
        )
    return asset, True


async def get_video_asset_by_slack_file(
    engine: AsyncEngine, draft_id: int, slack_file_id: str
) -> VideoAsset | None:
    """Return a draft's video asset for a Slack file ID, if present."""
    async with engine.connect() as conn:
        row = (
            await conn.execute(
                text(
                    "SELECT draft_id, slack_file_id, thread_ts, path, role, mime_type, size_bytes, "
                    "duration_seconds, width, height, status, review, message_ts "
                    "FROM video_assets WHERE draft_id = :draft_id AND slack_file_id = :slack_file_id"
                ),
                {"draft_id": draft_id, "slack_file_id": slack_file_id},
            )
        ).fetchone()
    if row is None:
        return None
    return _video_asset_from_row(row)


async def count_drafts_for_action(engine: AsyncEngine, action_type_name: str) -> int:
    async with engine.connect() as conn:
        row = (
            await conn.execute(
                text(
                    "SELECT count(*) FROM drafts d "
                    "JOIN action_types at ON at.id = d.action_type_id "
                    "WHERE at.name = :n"
                ),
                {"n": action_type_name},
            )
        ).fetchone()
    return int(row[0])
