"""Drafts — Draft dataclass + persist helpers + lookups."""

import json
from dataclasses import dataclass, field
from typing import Literal

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

Language = Literal["NL", "FR", "EN"]


@dataclass(frozen=True)
class Draft:
    """A single piece of marketing content generated by the agent."""

    action_type_name: str  # must match a seeded action_types.name
    channel: str  # e.g., "tiktok", "instagram", "email", "seo"
    language: Language
    copy: str
    asset_path: str | None  # filesystem path or None for text-only
    generation_cost_cents: int  # rounded; Claude tokens cost converted
    brand_score: int  # 0-100, set by brand-quality gate
    visual_truthfulness_pass: bool  # True for text-only drafts
    metadata: dict = field(default_factory=dict)


def draft_insert_params(draft: Draft) -> dict:
    """Return the shared SQL parameters for inserting an immutable draft variant."""
    return {
        "channel": draft.channel,
        "language": draft.language,
        "copy": draft.copy,
        "asset_path": draft.asset_path,
        "generation_cost_cents": draft.generation_cost_cents,
        "brand_score": draft.brand_score,
        "visual_truthfulness_pass": draft.visual_truthfulness_pass,
        "metadata": json.dumps(draft.metadata or {}),
    }


async def persist_draft(engine: AsyncEngine, draft: Draft) -> int:
    """Insert a draft row, return its id. Raises ValueError if action_type unknown."""
    async with engine.begin() as conn:
        action_id_row = (
            await conn.execute(
                text("SELECT id FROM action_types WHERE name = :n"),
                {"n": draft.action_type_name},
            )
        ).fetchone()
        if action_id_row is None:
            raise ValueError(f"unknown action_type: {draft.action_type_name!r}")
        action_type_id = action_id_row[0]

        new_id_row = (
            await conn.execute(
                text(
                    "INSERT INTO drafts "
                    "(action_type_id, channel, language, copy, asset_path, "
                    " generation_cost_cents, brand_score, visual_truthfulness_pass, metadata) "
                    "VALUES (:action_type_id, :channel, :language, :copy, :asset_path, "
                    ":generation_cost_cents, :brand_score, :visual_truthfulness_pass, "
                    "CAST(:metadata AS JSONB)) "
                    "RETURNING id"
                ),
                {
                    "action_type_id": action_type_id,
                    **draft_insert_params(draft),
                },
            )
        ).fetchone()
    return int(new_id_row[0])


async def count_drafts_for_action(engine: AsyncEngine, action_type_name: str) -> int:
    async with engine.connect() as conn:
        row = (
            await conn.execute(
                text(
                    "SELECT count(*) FROM drafts d "
                    "JOIN action_types at ON at.id = d.action_type_id "
                    "WHERE at.name = :n"
                ),
                {"n": action_type_name},
            )
        ).fetchone()
    return int(row[0])
